$(".chief").on("click",function(){
    $(".first").slideToggle();
})
$(".Co-Chair").on("click",function(){
    $(".seventh").slideToggle();
})
$(".Chairperson").on("click",function(){
    $(".eight").slideToggle();
})
$(".Technical").on("click",function(){
    $(".second").slideToggle();
})
$(".Workshop").on("click",function(){
    $(".third").slideToggle();
})
$(".Pubilicity").on("click",function(){
    $(".fourth").slideToggle();
})
$(".Finance").on("click",function(){
    $(".fifth").slideToggle();
})
$(".Registration").on("click",function(){
    $(".six").slideToggle();
})
$(".Student-Coordinators").on("click",function(){
    $(".Nine").slideToggle();
})